### ISSUE TITLE
redo lootcrate database tables

### ISSUE THREAD

**Issue by ArvidWedtstein** [ArvidWedtstein/ArkDashboard#111]
### Criterias / Ideas:
- A lootcrate can occur on multiple maps.
- Some lootcrates have same items on multiple maps
- Some lootcrate do not belong to any map (event lootcrates)
- A lootcrate can have multiple spawn locations per map
- The lootcrates all have different items, but many of them share much of the same items
- !! Integrate Dino Drops into lootcrates?  !!
- Some Boss drops count as lootcrate? (Ext King, Desert, Forest, Ice Titan, Lava Golem, Ice Queen), link to Dino Table?

### Info:
- 134 Different lootcratetypes
- The Center, The Island And Ragnarok have same supply drops
- Ragnarok uses the Supply Crates of both The Island and Scorched Earth. 
- Valguero uses the Supply Crates of The Island, Aberration, and Scorched Earth. 
- Additionally Lost Island uses the Supply Crates of both The Island and Scorched Earth. 
- Aberration has only crates underground and 4 surface beacons

- https://ark.wiki.gg/wiki/Explorer_Map/The_Island
- https://ark.fandom.com/wiki/Beacon_IDs

### TODO:
- [x] Make a plan for new tables
- [x] Delete old lootcrate tables (backup)
- [x] Integrate new tables into frontend
- [x] Add Obelisks to MapResources

Lootcrate tbl:
| Column | Type |
|--------|--------|
| id | BigInt |
| created_at | Datetime |
| updated_at | Datetime |
| name | text/nvarchar |

Lootcrate Maps/Dinos tbl:
| Column | Type |
|--------|--------|
| id | BigInt |
| created_at | Datetime |
| updated_at | Datetime |
| lootcrate_id | BigInt FK -> lootcrate tbl (nonnullable) | 
| map_id | BigInt FK -> map tbl (nullable) |
| lootcrate_id ?  | BigInt FK -> lootcrateset tbl ? (nonnullable) |
| coordinares ? | JSON (nullable) ? |

Lootcrate Items tbl:
| Column | Type |
|--------|--------|
| id | BigInt |
| created_at | Datetime |
| updated_at | Datetime |
| lootcrate_id| BigInt FK -> lootcrate tbl (nonnullable) | 
| item_id | BigInt FK -> item tbl (nonnullable) |
| category | text/nvarchar |
