### ISSUE TITLE
clean up dino table columns

### ISSUE THREAD

**Issue by ArvidWedtstein** [ArvidWedtstein/ArkDashboard#138]
### TODO:

- [ ] Merge "disable_tame" and flag "isTameable" to "tamable" column

- [ ] Remove potential duplicates

## Flags
- [ ] Integrate flags as columns?

Unique flags:
```
  "isBigDino",
  "isBossDino",
  "isCarnivore",
  "canBeTorpid",
  "allowRiding",
  "canBeDragged",
  "canDrag",
  "doStepDamage",
  "isTameable",
  "allowMountedWeaponry",
  "isAmphibious",
  "isWaterDino",
  "canBeWildTrappedWithFishBasket",
  "canBeTamedWithFishBasket",
  "allowFlyerLandedRider",
  "canMountOnHumans",
  "isFlyerDino",
  "preventNeuter",
  "isCorrupted",
  "isRaidDino",
  "isRobot",
  "preventCharacterBasing",
  "flyerAllowRidingInCaves",
  "dieIfLeftWater",
  "allowCarryFlyerDinos",
```

### All Columns:

- [ ] Add columns: 

- [ ] drag_weight, allowCarryFlyerDinos? canDrag? canBeDragged? (find solution for this)
tf does allowCarryFlyerDinos do?
can_drag column?
draggable column?
can_carry_flyer column? (recides if this dino can carry other flyers?)

```
Drag Weight is the "base" weight of a creature used to calculate the following:

    If a player can drag a creature's corpse.
    If the creature can be carried on a platform (Platform Saddle, Raft, Elevator etc.).
    If a creature can enter a [Boss Arena](https://ark.fandom.com/wiki/Boss_Arenas).
    If a creature can be carried by another creature (Quetzal, Kaprosuchus, Argentavis etc.).
```

------------
- [x] variants text array (replace with type?) 
- [x] taming_method text (use abbreviations or full name?)
- [ ] radiation_immune boolean
- [ ] TamedBaseHealthMultiplier?

```
x = remove
v = keep

v - admin_note
v - aff_inc  
v - affinity_needed
v - attack (dinos attacks. keep for now.)
v - baby_food_consumption_mult
base_points (unsure, not used anywhere yet)
v - base_stats
v - base_taming_time
v - bp
v - breedable (indicates that dino is breedable?)
v - can_destroy 
x - carryable_by (replace with drag_weight?)
v - created_at
v- default_dmg
v - default_swing_radius
v - description
v - diet
disable_food (not used anywhere)
x - disable_ko (not sure, not used anywhere)
v - disable_mult (used for calculating multipliers)
x - disable_tame (not used anywhere, replaced by tamable)
v - tamable (Creatures that can be tamed by humans)
v - egg_max
v - egg_min
v - exp_per_kill
flags (move to own columns?)
v - flee_threshold
v - food_consumption_base
v - food_consumption_mult
v - gestation_time
v - hitboxes
v - icon
v - id
v - image
v - incubation_time
v - mating_cooldown_max
v - mating_cooldown_min
v - maturation_time
v - mounted_weaponry
v- movement
v- multipliers
v - name
v - non_violent_food_affinity_mult (probably used for some calculations related to food consumption)
v - non_violent_food_rate_mult (used for some calculations)
v - released
v - ridable
v - synonyms
v - taming_ineffectiveness (used to calculate taming effectiveness)
v - taming_interval (used for calculating stuff)
v - taming_notice
targeting_team_name (not actually used yet.,)
v - tdps (rename to actual value.)
v - temperament
v - type (array of type, like water, ground, amphibious)
x - violent_tame (related to taming method?, false = 'Passive', true = 'Knockout'?, replace with taming_method column? (Knock-out (KO), Non-Violent (NV), Unique Non-Violent (UNV), diplodocus can be tamed with both?? )) 
x - x_variant (if dino has x_variant. replace with own column for variants?)
```
